name: Lint and test

on:
  - push
  - pull_request


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "yml2block/"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with poetry
        run: |
          poetry install --extras tests

      - name: Test that direct execution works
        run: |
          poetry run python yml2block --help

      - name: Run unit tests
        run: |
          poetry run pytest -v tests/unit_tests.py

      - name: Run integration tests
        run: |
          poetry run pytest -v tests/integration_tests.py
          
