name: Lint and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "yml2block/"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies with poetry
        run: |
          poetry install --extras tests
      - name: Test that direct execution works
        run: |
          poetry run python yml2block --help
      - name: Run integration tests
        run: |
          poetry run pytest tests/integration_tests.py
          
